# Generated by Django 5.0.4 on 2024-04-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_description'),
        ('user', '0007_alter_customuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name='user_team',
                to='team.team'),
        ),
    ]
