# Generated by Django 5.0.2 on 2024-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=250)),
                ('descrition',
                 models.TextField(
                     verbose_name='Valor predeterminado')),
            ],
        ),
    ]
