# Generated by Django 5.0.2 on 2024-02-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='descrition',
            new_name='description',
        ),
    ]
