# Generated by Django 5.0.2 on 2024-02-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_post', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategoryPermission',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('blog_post',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='blog_post.blogpost')),
                ('category',
                 models.ForeignKey(
                     on_delete=models.SET(None),
                     to='category.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='postcategorypermission',
            constraint=models.UniqueConstraint(
                fields=(
                    'blog_post',
                    'category'),
                name='unique_post_category'),
        ),
    ]
