# Generated by Django 5.0.3 on 2024-03-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
        ('post_cat_permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategorypermission',
            name='permission',
            field=models.ForeignKey(
                default=None,
                on_delete=models.SET(None),
                to='permission.permission'),
        ),
    ]
