# Generated by Django 5.0.3 on 2024-03-05 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_blogpost_updated_date'),
        ('post_cat_permission', '0002_postcategorypermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategorypermission',
            name='blog_post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='post_category_permissions',
                to='blog_post.blogpost'),
        ),
    ]
