# Generated by Django 5.0.6 on 2024-05-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_remove_blogpost_excerpt'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='blog_post.blogpost'),
        ),
    ]
